"""empty message

Revision ID: 8953e6ce86ae
Revises: 1b2e32fbfe7c
Create Date: 2022-07-26 18:53:18.672057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8953e6ce86ae'
down_revision = '1b2e32fbfe7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_user_fkey', 'card', type_='foreignkey')
    op.drop_column('card', 'user')
    op.add_column('user', sa.Column('card', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'card', ['card'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'card')
    op.add_column('card', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('card_user_fkey', 'card', 'user', ['user'], ['id'])
    # ### end Alembic commands ###
